### ISSUE TITLE
Để prefix cho router để tránh việc API Endpoint trùng với url của web page

### ISSUE THREAD

**Issue by dungtran2** [CcccKaaaa/todo_angular_fastapi#1]
https://github.com/CcccKaaaa/todo_angular_fastapi/blob/9e1770c3ccfe64327bfb64d7a6301132b4ac3c4d/TODO_APP_BE/todo_app/todo_api.py#L34

**Comment by dungtran2** [comment]
router declaration shoud be
```python
todo_api = APIRouter('/api')
```

**Comment by chuonglm2012** [comment]
Solve with 9ebb10631da5823b58f6d33b9acd2fc6b7bd69c7
